"""RED: Public API snapshot test.

The snapshot set below is authoritative — every addition or removal of a
top-level public symbol in the SDK must update this single assertion.
"""

import mcbe_ws_sdk


def test_public_api_snapshot() -> None:
    assert set(mcbe_ws_sdk.__all__) == {
        "__version__",
        "AddonBridgeClient",
        "AddonBridgeProfile",
        "AddonBridgeService",
        "AddonBridgeSettings",
        "AddonMessageResult",
        "AddonControlHook",
        "BridgeClosedError",
        "BridgeError",
        "BridgeLimitError",
        "BridgeTimeoutError",
        "CommandRegistry",
        "ConfigurationError",
        "ConnectionAddonBridgeClient",
        "LegacyUiChatCallbackAdapter",
        "ConnectionHook",
        "ConnectionManager",
        "ConnectionState",
        "DefaultResponseSink",
        "EventBus",
        "FacadeLifecycleError",
        "FlowControlMiddleware",
        "FlowControlSettings",
        "FrameTooLargeError",
        "GatewaySettings",
        "MCBEWS_V1",
        "McbeOutboundDelivery",
        "McbeServerFacade",
        "McbeWsSdkError",
        "McbewsV1Delivery",
        "McbewsV1Profile",
        "McbewsV1Protocol",
        "MCBEWS_V1_MANIFEST",
        "MCBEWS_V1_WIRE_VECTORS",
        "MessageSurfaceConfig",
        "MinecraftCommandResponse",
        "MinecraftErrorFrame",
        "MinecraftProtocolHandler",
        "NoOpHook",
        "LegacyUiChatHook",
        "LegacyUiChatHookAdapter",
        "OutboundText",
        "PlayerMessageEvent",
        "ProtocolError",
        "ResponseKind",
        "ResponseSink",
        "RouteEnvelope",
        "SubscriptionToken",
        "SystemNotification",
        "ToolPlayerChannel",
        "ToolPlayerMessage",
        "ApprovalDecision",
        "SessionError",
        "SessionRequest",
        "SessionResponse",
        "TextResponseChunk",
        "TextResponseMessage",
        "TokenUsage",
        "UiChatMessage",
        "WebsocketTransportConfig",
        "WsEventType",
        "classify_tool_player_message",
        "configure_logging",
        "decode_approval_decision",
        "decode_session_request_chat",
        "decode_session_response_message",
        "decode_text_response_frame",
        "encode_approval_decision",
        "encode_text_response_commands",
        "encode_session_request_chat",
        "encode_session_response_command",
        "enqueue_response",
        "is_tool_player_channel_message",
        "load_manifest",
        "load_wire_vectors",
    }
