import {
  APPROVAL_ALLOW_CHAT_PREFIX,
  APPROVAL_DENY_CHAT_PREFIX,
  CAPABILITY_REQUEST_SCRIPT_EVENT_ID,
  CAPABILITY_RESPONSE_CHAT_PREFIX,
  COMMAND_LINE_BYTE_BUDGET,
  MCBEWS_V1_MANIFEST,
  MCBEWS_V1_WIRE_VECTORS,
  RESPONSE_BUFFER_TTL_MS,
  RESPONSE_MAX_BUFFERS,
  RESPONSE_MAX_CHUNKS_PER_MESSAGE,
  RESPONSE_MAX_MESSAGE_BYTES,
  RESPONSE_MAX_TOTAL_BUFFER_BYTES,
  SESSION_RESPONSE_MAX_COMMAND_BYTES,
  SESSION_REQUEST_CHAT_PREFIX,
  SESSION_REQUEST_SCRIPT_EVENT_ID,
  SESSION_RESPONSE_SCRIPT_EVENT_ID,
  TEXT_RESPONSE_SCRIPT_EVENT_ID,
  TEXT_RESPONSE_ALLOWED_ROLES,
  TRUSTED_BRIDGE_PLAYER_NAME,
  UI_CHAT_CHUNK_PREFIX,
  UPSTREAM_MAX_CONTENT_CODE_POINTS,
} from "./protocol";

export {
  APPROVAL_ALLOW_CHAT_PREFIX,
  APPROVAL_DENY_CHAT_PREFIX,
  CAPABILITY_REQUEST_SCRIPT_EVENT_ID,
  CAPABILITY_RESPONSE_CHAT_PREFIX,
  COMMAND_LINE_BYTE_BUDGET,
  MCBEWS_V1_MANIFEST,
  MCBEWS_V1_WIRE_VECTORS,
  RESPONSE_BUFFER_TTL_MS,
  RESPONSE_MAX_BUFFERS,
  RESPONSE_MAX_CHUNKS_PER_MESSAGE,
  RESPONSE_MAX_MESSAGE_BYTES,
  RESPONSE_MAX_TOTAL_BUFFER_BYTES,
  SESSION_RESPONSE_MAX_COMMAND_BYTES,
  SESSION_REQUEST_CHAT_PREFIX,
  SESSION_REQUEST_SCRIPT_EVENT_ID,
  SESSION_RESPONSE_SCRIPT_EVENT_ID,
  TEXT_RESPONSE_SCRIPT_EVENT_ID,
  TEXT_RESPONSE_ALLOWED_ROLES,
  TRUSTED_BRIDGE_PLAYER_NAME,
  UI_CHAT_CHUNK_PREFIX,
  UPSTREAM_MAX_CONTENT_CODE_POINTS,
} from "./protocol";

/** Deprecated aliases; values are owned by the generated protocol projection. */
export const BRIDGE_RESPONSE_PREFIX = CAPABILITY_RESPONSE_CHAT_PREFIX;
export const BRIDGE_UI_CHAT_PREFIX = UI_CHAT_CHUNK_PREFIX;
export const BRIDGE_REQUEST_MESSAGE_ID = CAPABILITY_REQUEST_SCRIPT_EVENT_ID;
export const BRIDGE_SENDER = TRUSTED_BRIDGE_PLAYER_NAME;
export const BRIDGE_MAX_CHUNK_CONTENT_LENGTH = UPSTREAM_MAX_CONTENT_CODE_POINTS;
export const BRIDGE_COMMAND_LINE_BYTE_BUDGET = COMMAND_LINE_BYTE_BUDGET;
export const BRIDGE_MAX_CHUNK_CONTENT_CODE_POINTS = UPSTREAM_MAX_CONTENT_CODE_POINTS;
export const TEXT_RESP_MESSAGE_ID = TEXT_RESPONSE_SCRIPT_EVENT_ID;
export const SESSION_REQ_MESSAGE_ID = SESSION_REQUEST_SCRIPT_EVENT_ID;
export const SESSION_RESP_MESSAGE_ID = SESSION_RESPONSE_SCRIPT_EVENT_ID;
export const SESSION_REQ_PREFIX = SESSION_REQUEST_CHAT_PREFIX;
export const TOOL_APPROVE_PREFIX = APPROVAL_ALLOW_CHAT_PREFIX;
export const TOOL_DENY_PREFIX = APPROVAL_DENY_CHAT_PREFIX;
